### ISSUE TITLE
Sprawdziłem zadania

### ISSUE THREAD

**Issue by k-basinski** [zdanowski/tipn_zad_zdanowski#1]
Sprawdziłem wszystkie zadania i wszystko jest ok, bardzo dobrze. Dwie uwagi:

- Styl jest **koszmarny**. Stosowanie wcięć, enterów itp w odpowiednich miejscach poprawia czytelność kodu i ułatwia jego *reusability*. R Studio posiada opcję `reformat code`, która ułatwia to zadanie.

- Ten fragment:
```r
n <- 1
while(n<=a){
 print(rok[n])
  n <- n+2
}
```
można napisać dużo prościej: ` rok[seq(1, 12, 2)]`

**Comment by zdanowski** [comment]
Dziękuję za uwagi, następnym razem będę uważał.
